Python test with Coverage

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,7 +1,7 @@
 #! /usr/bin/env bash
 
 # CAUTION:
-# This file was generated by generator-canonical-webteam@3.3.2
+# This file was generated by generator-canonical-webteam@3.4.2
 # and should usually not be edited directly.
 #
 # This file was generated by the "canonical-webteam" Yeoman generator
@@ -14,7 +14,7 @@
 
 set -euo pipefail
 
-USAGE="How to use ./run v3.3.2
+USAGE="How to use ./run v3.4.2
 ===
 
   $ ./run \\
@@ -31,8 +31,11 @@ Commands
 - watch [-s|--watch-site]: Run \`yarn run watch\` (for jekyll sites, watch for changes with \`--watch-site\`)
 - build: Run \`yarn run build\`
 - test: Run \`yarn run test\`
+- test-python: Run \`yarn run test-python\`
+- lint-python: Run \`yarn run lint-python\`
 - stop: Stop any running containers
-- exec [-p|--expose-port PORT] <args>: Run a command in the development container (optionally exposing a port to the host)
+- exec [-r|--root] [-p|--expose-port PORT] <args>: Run a command in the development container (optionally exposing a port to the host)
+- yarn [-r|--root] [-p|--expose-port PORT] <script-name>: Run a yarn script from package.json
 - clean: Remove all images and containers, any installed dependencies and the .docker-project file
 - clean-cache: Empty cache files, which are saved between projects (eg, yarn)
 "
@@ -42,7 +45,7 @@ Commands
 ##
 
 # Define docker images versions
-dev_image="canonicalwebteam/dev:v1.6.3"
+dev_image="canonicalwebteam/dev:v1.6.4"
 if [ -n "${DOCKER_REGISTRY:-}" ]; then
     dev_image="${DOCKER_REGISTRY}/${dev_image}"
 fi
@@ -155,7 +158,7 @@ while [[ -n "${1:-}" ]] && [[ "${1:0:1}" == "-" ]]; do
             shift
         ;;
         -h|--help) echo "$USAGE"; exit ;;
-        -v|--version) echo "Generated from generator-canonical-webteam@3.3.2"; exit ;;
+        -v|--version) echo "Generated from generator-canonical-webteam@3.4.2"; exit ;;
         *) invalid "Option '${key}' not recognised." ;;
     esac
     shift
@@ -277,13 +280,14 @@ update_dependencies() {
     if [ -f package.json ]; then
         package_json_hash=$(${md5_command} package.json | cut -c1-8)
         if [ -d node_modules ]; then
-            yarn_dependencies_hash=$(find node_modules -type f -print0 | sort -z | xargs -0 ${md5_command} | ${md5_command} | cut -c1-8)-${package_json_hash}
+            yarn_dependencies_hash=$(find node_modules -type f ! -wholename 'node_modules/.cache/*' -print0 | sort -z | xargs -0 ${md5_command} | ${md5_command} | cut -c1-8)-${package_json_hash}
         fi
         if [ -z "${yarn_dependencies_hash:-}" ] || [ ! -f .yarn.${project}.hash ] || [ "${yarn_dependencies_hash}" != "$(cat .yarn.${project}.hash)" ]; then
             echo "Installing new Yarn dependencies"
             run_as_user "" yarn install --force ${yarn_proxy}
-            yarn_dependencies_hash=$(find node_modules -type f -print0 | sort -z | xargs -0 ${md5_command} | ${md5_command} | cut -c1-8)-${package_json_hash}
+            yarn_dependencies_hash=$(find node_modules -type f ! -wholename 'node_modules/.cache/*' -print0 | sort -z | xargs -0 ${md5_command} | ${md5_command} | cut -c1-8)-${package_json_hash}
             echo ${yarn_dependencies_hash} > .yarn.${project}.hash
+            echo "Saved ${yarn_dependencies_hash} to .yarn.${project}.hash"
         else
             echo "Yarn dependencies haven't changed. To force an update, delete .yarn.${project}.hash."
         fi
@@ -468,6 +472,48 @@ case $run_command in
             echo "==="
         fi
     ;;
+    "test-python")
+        update_dependencies
+
+        test_error=false
+
+        # Run node tests
+        echo "- Running python tests"
+        run_as_user "" yarn run test-python || test_error=true
+
+        # Report success or failure
+        if ${test_error}; then
+            echo "==="
+            echo "Tests failed"
+            echo "==="
+            exit 1
+        else
+            echo "==="
+            echo "Tests succeeded"
+            echo "==="
+        fi
+    ;;
+    "lint-python")
+        update_dependencies
+
+        lint_error=false
+
+        # Run node tests
+        echo "- Running python lint"
+        run_as_user "" yarn run lint-python || lint_error=true
+
+        # Report success or failure
+        if ${lint_error}; then
+            echo "==="
+            echo "Lint failed"
+            echo "==="
+            exit 1
+        else
+            echo "==="
+            echo "Lint succeeded"
+            echo "==="
+        fi
+    ;;
     "clean")
         echo "Remove hash files"
         rm -rf .*.hash
@@ -508,6 +554,7 @@ case $run_command in
     "exec")
         expose_ports=""
         run_as_root=false
+
         while [[ -n "${1:-}" ]] && [[ "${1:0:1}" == "-" ]]; do
             key="$1"
 
@@ -525,12 +572,43 @@ case $run_command in
             shift
         done
 
+        update_dependencies
         start_django_db
 
         if ${run_as_root}; then
             docker_run "${expose_ports}" $@
         else
             run_as_user "${expose_ports}" $@
+        fi
+    ;;
+    "yarn")
+        expose_ports=""
+        run_as_root=false
+
+        while [[ -n "${1:-}" ]] && [[ "${1:0:1}" == "-" ]]; do
+            key="$1"
+
+            case $key in
+                -r|--root)
+                    run_as_root=true
+                ;;
+                -p|--expose-port)
+                    if [ -z "${2:-}" ]; then invalid "Missing port number. Usage: --expose-port XXXX"; fi
+                    expose_ports="${expose_ports} --publish ${2}:${2}"
+                    shift
+                ;;
+                *) invalid "Option '${key}' not recognised." ;;
+            esac
+            shift
+        done
+
+        update_dependencies
+        start_django_db
+
+        if ${run_as_root}; then
+            docker_run "${expose_ports}" yarn run $@
+        else
+            run_as_user "${expose_ports}" yarn run $@
         fi
     ;;
     *) invalid "Command '${run_command}' not recognised." ;;
